src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("datetime")]
    #[Assert\GreaterThanOrEqual("today")]
    private $date_heure_depart;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("datetime")]
    #[Assert\GreaterThan(propertyPath:"date_heure_depart")]
    private $date_heure_fin;

    #[ORM\Column(type: 'integer')]
    #[Assert\GreaterThan(value:30)]
    private $prix_total;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("datetime")]
    private $date_enregistrement;


    #[ORM\ManyToOne(targetEntity:Vehicule::class, inversedBy:"commandes", cascade:["persist"])]
    private $vehicule ;

    #[ORM\ManyToOne(targetEntity:User::class, inversedBy:"commandes", cascade:["persist"])]
    private $user ;


        public function __construct()
    {
        $tz = new \DateTimeZone('Europe/Paris');
        $now = new \DateTime();
        $now->setTimezone($tz);	
        $this->setDateEnregistrement($now);
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateHeureDepart(): ?\DateTimeInterface
    {
        return $this->date_heure_depart;
    }

    public function setDateHeureDepart(\DateTimeInterface $date_heure_depart): self
    {
        $this->date_heure_depart = $date_heure_depart;

        return $this;
    }

    public function getDateHeureFin(): ?\DateTimeInterface
    {
        return $this->date_heure_fin;
    }

    public function setDateHeureFin(\DateTimeInterface $date_heure_fin): self
    {
        $this->date_heure_fin = $date_heure_fin;

        return $this;
    }

    public function getPrixTotal(): ?int
    {
        return $this->prix_total;
    }

    public function setPrixTotal(int $prix_total): self
    {
        $this->prix_total = $prix_total;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getVehicule(): ?Vehicule
    {
        return $this->vehicule;
    }

    public function setVehicule(?Vehicule $vehicule): self
    {
        $this->vehicule = $vehicule;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/CommandeType.php
<?php

namespace App\Form;

use DateTime;
use App\Entity\User;
use App\Entity\Commande;
use App\Entity\Vehicule;
use App\Twig\FiltreExtension;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class CommandeType extends AbstractType
{

    public function __construct(private FiltreExtension $filter){}

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_heure_depart' , DateTimeType::class , [
                'widget' => 'single_text',
                "attr" => [
                    "min" => (new DateTime())->format("Y-m-d H:i"), // permet de desactiver les dates avanat aujourdhui dasn les calendriers
        
                ]
            ])
            ->add('date_heure_fin', DateTimeType::class , [
                'widget' => 'single_text',
                "attr" => [
                    "min" => (new DateTime())->format("Y-m-d H:i"), // permet de desactiver les dates avanat aujourdhui dasn les calendriers
                ]
            ])
            ->add('vehicule' , EntityType::class , [
                'class' => Vehicule::class,
                // 'choice_label' => 'titre',
                'choice_label' => function ($vehicule) {
                    return $vehicule->getTitre() ." - " .$this->filter->deviseFr($vehicule->getPrixJournalier());
                }
            ])
            ->add('user' , EntityType::class , [
                'class' => User::class,
                'choice_label' => 'pseudo',
            ])
            ->add('save' , SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller ;

use DateTime;
use App\Entity\Commande;
use App\Entity\Vehicule;
use App\Form\CommandeType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CommandeController extends AbstractController{

    /*
     * associer à une methode plusieurs routes en meme temps sur une methode + ParamConverter
    */

    // ---------- DEBUT CRUD - CREATE + UPDATE - AJOUTER et MODIFIER  ----------NOUVELLE METHODE---//
    #[Route("/admin/commande/new" , name:"commande_new")]
    #[Route("/admin/commande/update{id}" , name:"commande_update")]
    public function new(Request $request ,EntityManagerInterface $em , Commande $commande = null):Response{

        // si /admin/commande/new => $commande = null
        // si /admin/commande/update/{id} => $commande = $em->getRepository(Commande::class)->find($id); donc $comande = {}
        if($commande === null){
            $commande = new Commande();
            $commande->setDateHeureDepart( new DateTime())
                     ->setDateHeureFin(new DateTime());
        }

        $form = $this->createForm(CommandeType::class, $commande);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

        //recupere la date de debut et la date de fin
        // recupere le prix journalier qui vient du vehicule choisit 

        //multiplication = nbr de jour * prix journalier 

            $dt_debut = $form->get("date_heure_depart")->getData();
            $dt_fin = $form->get("date_heure_fin")->getData();
            $interval = $dt_debut->diff($dt_fin);
            $interval->format("%d");
            $nbJours = $interval->days ; 

            if($nbJours < 1){
                $this->addFlash("message" , "une reservation doit durer 24h au minimum");
                //return $this->redirectToRoute("commande_new" , $request->query->all());
            }
            $listevehiculeLoue = $em->getRepository(Commande::class)->listeVehiculeLoue($dt_debut ,$dt_fin );
            $vehicule = $form->get("vehicule")->getData();
            if(in_array( $vehicule->getId() , $listevehiculeLoue)){

                $listevehiculeDisponible = $em->getRepository(Vehicule::class)->findByVehiculeDisponibles($listevehiculeLoue );
                // $listevehiculeDisponible
                $this->addFlash("message" , "le véhicule demandé est déjà réservé");
                $this->addFlash("vehicules" , ["disponibles" => $listevehiculeDisponible] );
                //return $this->redirectToRoute("commande_new" , $request->query->all());
            }

            // dd($listevehiculeLoue , $listevehiculeDisponible); 

            if(!in_array( $vehicule->getId() , $listevehiculeLoue) && $nbJours >= 1){
                $prix_journalier = $vehicule->getPrixJournalier();

                $commande->setPrixTotal($nbJours * $prix_journalier);
                $em->persist($commande);
                $em->flush();
                return $this->redirectToRoute("commande_list");
                // regarder dans la base de données 
            }
           
        }

        return $this->render("commande/new.html.twig" , [
            "form" => $form->createView(),
            "id"   => $commande->getId()
        ]);
    }
    // ---------- FIN CRUD - CREATE - AJOUTER -------------//


    // ---------- DEBUT CRUD - CREATE - AFFICHER -------------//
    #[Route("/admin/commande/list" , name:"commande_list")]
    public function list(EntityManagerInterface $em):Response{
        $commandes = $em->getRepository(Commande::class)->findAll();

    return $this->render("commande/list.html.twig" , compact("commandes"));
    //["commandes" => $commandes]

    }
    // ---------- FIN CRUD - CREATE - AFFICHER -------------//




    // ---------- DEBUT CRUD - UPDATE - MODIFIER ancien -------------//

    // ---------- FIN CRUD - UPDATE - MODIFIER -------------//




    // ---------- DEBUT CRUD - UPDATE - MODIFIER ---------NOUVELLE METHODE----//
    #[Route("/admin/commande/suppr{id}" , name:"commande_suppr")]
    public function delete(Commande $commandeASupprimer , EntityManagerInterface $em){

        if($commandeASupprimer !== null){
            $em->remove($commandeASupprimer);
            $em->flush();
        }
        return $this->redirectToRoute("commande_list");
    }
    // ---------- FIN CRUD - UPDATE - MODIFIER ---------NOUVELLE METHODE----//

        
    





    
}

templates/commande/list.html.twig
{% extends 'back-office.html.twig' %}

{% block title %}Liste des commandes{% endblock %}

{% block body %}
    <h1>Liste des commandes</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th style="width:5%">id</th>
                <th style="width:10%">membre</th>
                <th style="width:10%">vehicule</th>
                <th style="width:15%">debut</th>
                <th style="width:10%">fin</th>
                <th style="width:25%">total</th>
                {# <th style="width:10%">dt creation</th> #}
                <th style="width:15%">actions</th>
            </tr>
        </thead>
        <tbody>
            {% for commande in commandes %}
            <tr>
                <td>{{commande.id}}</td>
                <td>{{commande.user.id}} - {{ commande.user.pseudo }}</td>
                <td>{{commande.vehicule.id}} - {{ commande.vehicule.titre }}</td>
                <td>{{commande.dateHeureDepart | date("d/m/Y H:i:s")}}</td>
                <td>{{commande.dateHeureFin | date("d/m/Y H:i:s")}}</td>
                <td>{{commande.prixTotal | deviseFr}}</td>
                {# <td>{{ membre.roles | join(",")}}</td> #}
                {# <td class="align-middle">{{ membre.dateEnregistrement | date("d/m/Y H:i:s")}}</td> #}

                <td>
                    {% include "commun/action.html.twig" with {"id" : commande.id , "update": "commande_update", "delete": "commande_suppr" } %}
                </td>
            </tr>

            {% else %}
                <tr>
                    <td colspan="7">aucun membres enregistré pour le moment</td>
                </tr>

            {% endfor %}
        </tbody>

    </table>
{% endblock %}

templates/commande/new.html.twig
{% extends 'back-office.html.twig' %}

{% block title %}Ajouter une nouvelle commande{% endblock %}

{% block body %}
    <h1>
        {{ id ? "Modifier la commande numéro " ~ id : "créer une nouvelle commande"}}
    </h1>
    {% for message in app.flashes("message") %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
    {% for vehicule in app.flashes("vehicules") %}
        <div class="alert alert-info">
            <div>liste des véhicules disponibles sur le créneau demandé</div>
            <ul>
                {% for v in vehicule.disponibles %}
                    <li>{{ v.titre }}</li>
                     {% else %}
                    <li>Aucun véhicule en stocke pour répondre à votre demande</li>
                {% endfor %}
            </ul>
        </div>
   
        
    {% endfor %}
    {{ form(form)}}
{% endblock %}