src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 200)]
    #[Assert\Length(min:3)]
    private $titre;

    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\Length(min:3)]
    private $marque;

    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\Length(min:3)]
    private $modele;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'string', length: 200)]
    #[Assert\Length(min:3)]
    private $photo;

    #[ORM\Column(type: 'integer')]
    #[Assert\GreaterThan(value:30)]
    private $prix_journalier;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("datetime")]
    private $date_enregistrement; // create => constructeur

    #[ORM\OneToMany(targetEntity:Commande::class , mappedBy:"vehicule")]
    private $commandes ;

    public function __construct()
    {
        $tz = new \DateTimeZone('Europe/Paris');
        $now = new \DateTime();
        $now->setTimezone($tz);	
        $this->setDateEnregistrement($now);
        $this->commandes = new ArrayCollection(); 

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): self
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setVehicule($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getVehicule() === $this) {
                $commande->setVehicule(null);
            }
        }

        return $this;
    }
}

templates/front/commande.html.twig
{% extends "base.html.twig"  %}


{% block title %} Synthèse {% endblock %}


{% block body %}
<h2>Finaliser votre location</h2>
{{form(form)}}
{% endblock %}

templates/front/index.html.twig
{% extends "base.html.twig"  %}


{% block title %} Page d'accueil {% endblock %}


{% block body %}
  <!-- Background image -->
  <div
    class="p-5 text-center bg-image"
    {# <img src="{{ asset('img/accueil.jpeg') }}" alt=« «  style="height: 400px;> #}
    style="background-image: url('https://cdn.teslanorth.com/wp-content/uploads/2021/10/tesla-hero-desktop.jpeg');height: 390px; width:100%; background-repeat: no-repeat;">
    
    <div class="mask">
      <div class="d-flex justify-content-center align-items-center h-100">
        <div class="text-white">
          <h1 class="mb-3">TESLA LOCA</h1>
          <h4 class="mb-3">Location de voiture TESLA 24/24 et 7j/7</h4>
          {# <a class="btn btn-outline-light btn-lg" href="#!" role="button"
          >Call to action</a
          > #}
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->

    <div class="d-flex justify-content-center moteurDeRecherche" style="min">
        {% include "commun/form-search.html.twig" %}
        {# <h1>Page d'accueil <small class="fs-5">{{app.user ? "bienvenu " ~ app.user.prenom : ""}}<small></h1> #}

    </div>


{% endblock %}

templates/front/registration.html.twig
{% extends "base.html.twig"  %}


{% block title %}Inscription {% endblock %}


{% block body %}
 <main class="row">
    <div class="offset-2 col-4"> 
    <h2 class="h3 mb-3 font-weight-normal">Créer un compte membre</h2>
        {{ form(formInscription)}}
    </div>

    <div class="col-4"> 
        {% include "commun/form-login.html.twig" %}
    </div>
 </main>


{% endblock %}

templates/front/resultats.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des vehicules disponibles{% endblock %}

{% block body %}
  <!-- Background image -->
  <div
    class="p-5 text-center bg-image"
    {# <img src="{{ asset('img/accueil.jpeg') }}" alt=« «  style="height: 400px;> #}
    style="background-image: url('https://cdn.teslanorth.com/wp-content/uploads/2021/10/tesla-hero-desktop.jpeg');height: 390px; width:100%; background-repeat: no-repeat;">
    
    <div class="mask">
      <div class="d-flex justify-content-center align-items-center h-100">
        <div class="text-white">
          {# <h1 class="mb-3">Bienvenue à bord</h1>
          <h4 class="mb-3">Location de voiture TESLA 24/24 et 7j/7</h4> #}
          {# <a class="btn btn-outline-light btn-lg" href="#!" role="button"
          >Call to action</a
          > #}
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->


    <div class="d-flex justify-content-center moteurDeRecherche" style="min">
        {% include "commun/form-search.html.twig" %}
    </div>

    <h1 class="text-center" style="margin-bottom:30px">Liste des vehicules disponibles</h1>

            {% for vehicule in vehicules %}
            <article class="row" style="padding-bottom:50px; margin-bottom:50px; border-bottom:1px solid #DCDCDC">
                <figure class="offset-3 col-3"> 
                    <img src="/upload{{ asset(vehicule.photo)}}" alt="" class="img-fluid">
                </figure>
                <div class="col-3">
                    <h2>{{vehicule.titre}}</h2>
                    <p>{{vehicule.prixJournalier | deviseFr}}</p>
                    <p>{{vehicule.description}}</p>
                    <a href="{{ path("home_rent" ,  {"id" :  vehicule.id }) }}" class="btn btn-secondary" style="border-radius:0px">Louer</a>
                </div>
            </article>
            {% else %}
                    <p class="alert alert-danger">aucun vehicule enregistré pour le moment</p>
            {% endfor %}
{% endblock %}